In [5]:
import numpy as np

#Question 1
arrayQ1 = np.full((2,2),10)
print(arrayQ1)

[[10 10]
 [10 10]]


In [10]:
#Question 2
arrayQ2 = np.random.random((3,4))
print(arrayQ2)

[[0.88897574 0.20594515 0.93321497 0.71048786]
 [0.42380626 0.55556228 0.50375089 0.85097618]
 [0.84804228 0.63314245 0.88339827 0.6219274 ]]


In [16]:
#Question 3
arrayQ3one = np.ones((3,8))
arrayQ3zero = np.zeros((5,3))
print("Array of ones: \n",arrayQ3one)
print("\nArray of zeros: \n", arrayQ3zero)

Array of ones: 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Array of zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#Question 4
arrayQ4 = np.random.random((6,3))
print("Array before transpose: \n",arrayQ4)
print("\nArray after transpose: \n",arrayQ4.T)

Array before transpose: 
 [[0.51689592 0.54205524 0.54635684]
 [0.00865089 0.32115342 0.98546626]
 [0.85559686 0.21839259 0.94588429]
 [0.35257524 0.51560795 0.40794974]
 [0.22104322 0.46603014 0.61574863]
 [0.60602015 0.29251755 0.74813371]]

Array after transpose: 
 [[0.51689592 0.00865089 0.85559686 0.35257524 0.22104322 0.60602015]
 [0.54205524 0.32115342 0.21839259 0.51560795 0.46603014 0.29251755]
 [0.54635684 0.98546626 0.94588429 0.40794974 0.61574863 0.74813371]]


In [24]:
#Question 5
n = int(input("Enter n: "))
p = int(input("Enter p: "))
m = int(input("Enter m: "))
arrayQ5np = np.random.random((n,p))
arrayQ5pm = np.random.random((p,m))
print("First array: \n",arrayQ5np)
print("\nSecond array: \n",arrayQ5pm)
print("\nDot Product: \n",np.dot(arrayQ5np,arrayQ5pm))

Enter n: 2
Enter p: 3
Enter m: 4
First array: 
 [[0.07684481 0.92450317 0.66678458]
 [0.43553554 0.8476876  0.33552898]]

Second array: 
 [[0.03543619 0.91577388 0.94815886 0.71463419]
 [0.12893103 0.34088771 0.22879906 0.99228994]
 [0.30583323 0.6448318  0.31971036 0.38565455]]

Dot Product: 
 [[0.32584511 0.81548814 0.49756448 1.22943963]
 [0.22734287 0.90417811 0.71417909 1.28179874]]


In [25]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [26]:
%cd '/content/drive/MyDrive/git_repos/data-science-toolkit'
!mv "../../Colab Notebooks/Tuto 3.ipynb" "./"

/content/drive/MyDrive/git_repos/data-science-toolkit


In [27]:
!git config --global user.email "limjunbin05@gmail.com"
!git config --global user.name "JunBin05"

In [33]:
!git add Tuto\ 3.ipynb
!git commit -m "Push Tutorial 3 of WIX1007 Data Science to Github"

[library/numpy 433cc14] Push Tutorial 3 of WIX1007 Data Science to Github
 1 file changed, 1 insertion(+), 1 deletion(-)


In [38]:
!git push https://JunBin05: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@github.com/JunBin05/data-science-toolkit.git main

Everything up-to-date


In [40]:
!git status
!git add Tuto\ 3.ipynb python_basics.ipynb
!git commit -m "Push Tutorial 3 of WIX1007 Data Science to Github"

On branch library/numpy
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Tuto 3.ipynb
	modified:   python_basics.ipynb

no changes added to commit (use "git add" and/or "git commit -a")
[library/numpy 2432289] Save notebook changes before merge
 2 files changed, 2 insertions(+), 2 deletions(-)
 rewrite python_basics.ipynb (63%)
