In [1]:
import numpy as np

#Question 1
arrayQ1 = np.full((2,2),10)
print(arrayQ1)

[[10 10]
 [10 10]]


In [2]:
#Question 2
arrayQ2 = np.random.random((3,4))
print(arrayQ2)

[[0.05873893 0.12558961 0.53325611 0.93082056]
 [0.96949089 0.89388056 0.38529403 0.92145079]
 [0.0295467  0.34477511 0.50540163 0.20485755]]


In [3]:
#Question 3
arrayQ3one = np.ones((3,8))
arrayQ3zero = np.zeros((5,3))
print("Array of ones: \n",arrayQ3one)
print("\nArray of zeros: \n", arrayQ3zero)

Array of ones: 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Array of zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#Question 4
arrayQ4 = np.random.random((6,3))
print("Array before transpose: \n",arrayQ4)
print("\nArray after transpose: \n",arrayQ4.T)

Array before transpose: 
 [[0.69398145 0.77611331 0.939352  ]
 [0.65700014 0.19925325 0.29156216]
 [0.83404351 0.89552989 0.11113478]
 [0.92294953 0.05717278 0.7499998 ]
 [0.17263209 0.19497955 0.24509541]
 [0.08018291 0.98077738 0.45058421]]

Array after transpose: 
 [[0.69398145 0.65700014 0.83404351 0.92294953 0.17263209 0.08018291]
 [0.77611331 0.19925325 0.89552989 0.05717278 0.19497955 0.98077738]
 [0.939352   0.29156216 0.11113478 0.7499998  0.24509541 0.45058421]]


In [5]:
#Question 5
n = int(input("Enter n: "))
p = int(input("Enter p: "))
m = int(input("Enter m: "))
arrayQ5np = np.random.random((n,p))
arrayQ5pm = np.random.random((p,m))
print("\nFirst array: \n",arrayQ5np)
print("\nSecond array: \n",arrayQ5pm)
print("\nDot Product: \n",np.dot(arrayQ5np,arrayQ5pm))

Enter n: 2
Enter p: 3
Enter m: 4

First array: 
 [[0.94261084 0.53631038 0.08103989]
 [0.69831568 0.77973215 0.49335278]]

Second array: 
 [[0.30508347 0.73756148 0.89372453 0.57223219]
 [0.4230282  0.40125152 0.83658575 0.62569748]
 [0.20834427 0.9804745  0.44004291 0.74663841]]

Dot Product: 
 [[0.5313336  0.98988635 1.32676507 0.93546781]
 [0.64568049 1.31163927 1.49351105 1.25583128]]


In [6]:
from google.colab import drive
drive.mount('/content/drive')
%cd '/content/drive/MyDrive/git_repos/data-science-toolkit'
!mv "../../Colab Notebooks/Tuto_3_clean.ipynb" "./"
!git config --global user.email "limjunbin05@gmail.com"
!git config --global user.name "JunBin05"

Mounted at /content/drive
/content/drive/MyDrive/git_repos/data-science-toolkit


In [8]:
import os
os.environ["GITHUB_TOKEN"] = "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"

In [ ]:
!git add Tuto_3_clean.ipynb
!git commit -m "Hope it can push Tuto 3"
!git push